version: '3'
services:
  cdn:
    build:
      context: cdn
    ports:
      - "5050:5050"
  server:
    build:
      context: server
    ports:
      - "5000:5000"
    depends_on:
      - cdn
  client:
    build:
      context: client
    ports:
      - "80:80"
    depends_on:
      - server
